spring:
  datasource:
    url: jdbc:mysql://39.96.222.232/knowapi
    username: cmy
    password: admin
    druid:
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 200
beetlsql:
  enabled: false
beetl:
  resource-auto-check: true
#beetl:
#  suffix: btl
mybatis:
  type-aliases-package: com.cmy.knowapi.model
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
mapper:
  #  mappers: tk.mybatis.mapper.common.Mapper
  identity: mysql
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql